spring:
  application:
    name: chargeback-ui
security:
  basic:
    enabled: false
server:
  port: ${PORT:${SERVER_PORT:8080}} 

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
